// Code generated by ogen, DO NOT EDIT.

package constapi

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Probe
type Probe struct {
	State    string    `json:"state"`
	Code     int       `json:"code"`
	Ratio    float64   `json:"ratio"`
	Enabled  bool      `json:"enabled"`
	Empty    struct{}  `json:"empty"`
	Optional OptString `json:"optional"`
}

// GetState returns the value of State.
func (s *Probe) GetState() string {
	return s.State
}

// GetCode returns the value of Code.
func (s *Probe) GetCode() int {
	return s.Code
}

// GetRatio returns the value of Ratio.
func (s *Probe) GetRatio() float64 {
	return s.Ratio
}

// GetEnabled returns the value of Enabled.
func (s *Probe) GetEnabled() bool {
	return s.Enabled
}

// GetEmpty returns the value of Empty.
func (s *Probe) GetEmpty() struct{} {
	return s.Empty
}

// GetOptional returns the value of Optional.
func (s *Probe) GetOptional() OptString {
	return s.Optional
}

// SetState sets the value of State.
func (s *Probe) SetState(val string) {
	s.State = val
}

// SetCode sets the value of Code.
func (s *Probe) SetCode(val int) {
	s.Code = val
}

// SetRatio sets the value of Ratio.
func (s *Probe) SetRatio(val float64) {
	s.Ratio = val
}

// SetEnabled sets the value of Enabled.
func (s *Probe) SetEnabled(val bool) {
	s.Enabled = val
}

// SetEmpty sets the value of Empty.
func (s *Probe) SetEmpty(val struct{}) {
	s.Empty = val
}

// SetOptional sets the value of Optional.
func (s *Probe) SetOptional(val OptString) {
	s.Optional = val
}
