// Code generated by ogen, DO NOT EDIT.

package constapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetProbe implements getProbe operation.
//
// GET /probe
func (UnimplementedHandler) GetProbe(ctx context.Context) (r *Probe, _ error) {
	return r, ht.ErrNotImplemented
}
