// Code generated by ogen, DO NOT EDIT.

package constapi

import (
	"math/bits"
	"strconv"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/ogen-go/ogen/json"
	"github.com/ogen-go/ogen/validate"
)

// Encode encodes string as json.
func (o OptString) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	e.Str(string(o.Value))
}

// Decode decodes string from json.
func (o *OptString) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptString to nil")
	}
	o.Set = true
	v, err := d.Str()
	if err != nil {
		return err
	}
	o.Value = string(v)
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptString) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptString) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *Probe) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *Probe) encodeFields(e *jx.Encoder) {
	{
		e.FieldStart("state")
		e.Str("ready")
	}
	{
		e.FieldStart("code")
		e.Int(42)
	}
	{
		e.FieldStart("ratio")
		e.Float64(1.5)
	}
	{
		e.FieldStart("enabled")
		e.Bool(true)
	}
	{
		e.FieldStart("empty")
		e.Null()
	}
	{
		e.FieldStart("optional")
		e.Str("optional")
	}
}

var jsonFieldsNameOfProbe = [6]string{
	0: "state",
	1: "code",
	2: "ratio",
	3: "enabled",
	4: "empty",
	5: "optional",
}

// Decode decodes Probe from json.
func (s *Probe) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode Probe to nil")
	}
	var requiredBitSet [1]uint8

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "state":
			requiredBitSet[0] |= 1 << 0
			if err := func() error {
				if err := d.Capture(func(d *jx.Decoder) error {
					value, err := d.Raw()
					if err != nil {
						return err
					}
					equal, err := json.Equal(value, []byte("\"ready\""))
					if err != nil {
						return err
					}
					if !equal {
						return errors.New("unexpected constant value")
					}
					return nil
				}); err != nil {
					return err
				}
				v, err := d.Str()
				s.State = string(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"state\"")
			}
		case "code":
			requiredBitSet[0] |= 1 << 1
			if err := func() error {
				if err := d.Capture(func(d *jx.Decoder) error {
					value, err := d.Raw()
					if err != nil {
						return err
					}
					equal, err := json.Equal(value, []byte("42"))
					if err != nil {
						return err
					}
					if !equal {
						return errors.New("unexpected constant value")
					}
					return nil
				}); err != nil {
					return err
				}
				v, err := d.Int()
				s.Code = int(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"code\"")
			}
		case "ratio":
			requiredBitSet[0] |= 1 << 2
			if err := func() error {
				if err := d.Capture(func(d *jx.Decoder) error {
					value, err := d.Raw()
					if err != nil {
						return err
					}
					equal, err := json.Equal(value, []byte("1.5"))
					if err != nil {
						return err
					}
					if !equal {
						return errors.New("unexpected constant value")
					}
					return nil
				}); err != nil {
					return err
				}
				v, err := d.Float64()
				s.Ratio = float64(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"ratio\"")
			}
		case "enabled":
			requiredBitSet[0] |= 1 << 3
			if err := func() error {
				if err := d.Capture(func(d *jx.Decoder) error {
					value, err := d.Raw()
					if err != nil {
						return err
					}
					equal, err := json.Equal(value, []byte("true"))
					if err != nil {
						return err
					}
					if !equal {
						return errors.New("unexpected constant value")
					}
					return nil
				}); err != nil {
					return err
				}
				v, err := d.Bool()
				s.Enabled = bool(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"enabled\"")
			}
		case "empty":
			requiredBitSet[0] |= 1 << 4
			if err := func() error {
				if err := d.Capture(func(d *jx.Decoder) error {
					value, err := d.Raw()
					if err != nil {
						return err
					}
					equal, err := json.Equal(value, []byte("null"))
					if err != nil {
						return err
					}
					if !equal {
						return errors.New("unexpected constant value")
					}
					return nil
				}); err != nil {
					return err
				}
				if err := d.Null(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"empty\"")
			}
		case "optional":
			if err := func() error {
				if err := d.Capture(func(d *jx.Decoder) error {
					value, err := d.Raw()
					if err != nil {
						return err
					}
					equal, err := json.Equal(value, []byte("\"optional\""))
					if err != nil {
						return err
					}
					if !equal {
						return errors.New("unexpected constant value")
					}
					return nil
				}); err != nil {
					return err
				}
				s.Optional.Reset()
				if err := s.Optional.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"optional\"")
			}
		default:
			return errors.Errorf("unexpected field %q", k)
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode Probe")
	}
	// Validate required fields.
	var failures []validate.FieldError
	for i, mask := range [1]uint8{
		0b00011111,
	} {
		if result := (requiredBitSet[i] & mask) ^ mask; result != 0 {
			// Mask only required fields and check equality to mask using XOR.
			//
			// If XOR result is not zero, result is not equal to expected, so some fields are missed.
			// Bits of fields which would be set are actually bits of missed fields.
			missed := bits.OnesCount8(result)
			for bitN := 0; bitN < missed; bitN++ {
				bitIdx := bits.TrailingZeros8(result)
				fieldIdx := i*8 + bitIdx
				var name string
				if fieldIdx < len(jsonFieldsNameOfProbe) {
					name = jsonFieldsNameOfProbe[fieldIdx]
				} else {
					name = strconv.Itoa(fieldIdx)
				}
				failures = append(failures, validate.FieldError{
					Name:  name,
					Error: validate.ErrFieldRequired,
				})
				// Reset bit.
				result &^= 1 << bitIdx
			}
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *Probe) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *Probe) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}
