// Code generated by ogen, DO NOT EDIT.

package unionapi

import (
	"github.com/go-faster/errors"
)

// NewOptNull returns new OptNull with value set to v.
func NewOptNull(v struct{}) OptNull {
	return OptNull{
		Value: v,
		Set:   true,
	}
}

// OptNull is optional struct{}.
type OptNull struct {
	Value struct{}
	Set   bool
}

// IsSet returns true if OptNull was set.
func (o OptNull) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNull) Reset() {
	var v struct{}
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptNull) SetTo(v struct{}) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNull) Get() (v struct{}, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNull) Or(d struct{}) struct{} {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/OrdinaryReference
type OrdinaryReference struct {
	RecordType OrdinaryReferenceRecordType `json:"record_type"`
	Review     OptNull                     `json:"review"`
}

// GetRecordType returns the value of RecordType.
func (s *OrdinaryReference) GetRecordType() OrdinaryReferenceRecordType {
	return s.RecordType
}

// GetReview returns the value of Review.
func (s *OrdinaryReference) GetReview() OptNull {
	return s.Review
}

// SetRecordType sets the value of RecordType.
func (s *OrdinaryReference) SetRecordType(val OrdinaryReferenceRecordType) {
	s.RecordType = val
}

// SetReview sets the value of Review.
func (s *OrdinaryReference) SetReview(val OptNull) {
	s.Review = val
}

type OrdinaryReferenceRecordType string

const (
	OrdinaryReferenceRecordTypeDraft    OrdinaryReferenceRecordType = "draft"
	OrdinaryReferenceRecordTypeTemplate OrdinaryReferenceRecordType = "template"
)

// AllValues returns all OrdinaryReferenceRecordType values.
func (OrdinaryReferenceRecordType) AllValues() []OrdinaryReferenceRecordType {
	return []OrdinaryReferenceRecordType{
		OrdinaryReferenceRecordTypeDraft,
		OrdinaryReferenceRecordTypeTemplate,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrdinaryReferenceRecordType) MarshalText() ([]byte, error) {
	switch s {
	case OrdinaryReferenceRecordTypeDraft:
		return []byte(s), nil
	case OrdinaryReferenceRecordTypeTemplate:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrdinaryReferenceRecordType) UnmarshalText(data []byte) error {
	switch OrdinaryReferenceRecordType(data) {
	case OrdinaryReferenceRecordTypeDraft:
		*s = OrdinaryReferenceRecordTypeDraft
		return nil
	case OrdinaryReferenceRecordTypeTemplate:
		*s = OrdinaryReferenceRecordTypeTemplate
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Reference
// Reference represents sum type.
type Reference struct {
	// Type selects the active sum variant, switch on this field.
	Type              ReferenceType
	OrdinaryReference OrdinaryReference
	ReviewedReference ReviewedReference
}

// ReferenceType is oneOf type of Reference.
type ReferenceType string

// Possible values for ReferenceType.
const (
	OrdinaryReferenceReference ReferenceType = "OrdinaryReference"
	ReviewedReferenceReference ReferenceType = "ReviewedReference"
)

// IsOrdinaryReference reports whether Reference is OrdinaryReference.
func (s Reference) IsOrdinaryReference() bool { return s.Type == OrdinaryReferenceReference }

// IsReviewedReference reports whether Reference is ReviewedReference.
func (s Reference) IsReviewedReference() bool { return s.Type == ReviewedReferenceReference }

// SetOrdinaryReference sets Reference to OrdinaryReference.
func (s *Reference) SetOrdinaryReference(v OrdinaryReference) {
	s.Type = OrdinaryReferenceReference
	s.OrdinaryReference = v
}

// GetOrdinaryReference returns OrdinaryReference and true boolean if Reference is OrdinaryReference.
func (s Reference) GetOrdinaryReference() (v OrdinaryReference, ok bool) {
	if !s.IsOrdinaryReference() {
		return v, false
	}
	return s.OrdinaryReference, true
}

// NewOrdinaryReferenceReference returns new Reference from OrdinaryReference.
func NewOrdinaryReferenceReference(v OrdinaryReference) Reference {
	var s Reference
	s.SetOrdinaryReference(v)
	return s
}

// SetReviewedReference sets Reference to ReviewedReference.
func (s *Reference) SetReviewedReference(v ReviewedReference) {
	s.Type = ReviewedReferenceReference
	s.ReviewedReference = v
}

// GetReviewedReference returns ReviewedReference and true boolean if Reference is ReviewedReference.
func (s Reference) GetReviewedReference() (v ReviewedReference, ok bool) {
	if !s.IsReviewedReference() {
		return v, false
	}
	return s.ReviewedReference, true
}

// NewReviewedReferenceReference returns new Reference from ReviewedReference.
func NewReviewedReferenceReference(v ReviewedReference) Reference {
	var s Reference
	s.SetReviewedReference(v)
	return s
}

// Ref: #/components/schemas/ReviewedReference
type ReviewedReference struct {
	RecordType string                  `json:"record_type"`
	Review     ReviewedReferenceReview `json:"review"`
}

// GetRecordType returns the value of RecordType.
func (s *ReviewedReference) GetRecordType() string {
	return s.RecordType
}

// GetReview returns the value of Review.
func (s *ReviewedReference) GetReview() ReviewedReferenceReview {
	return s.Review
}

// SetRecordType sets the value of RecordType.
func (s *ReviewedReference) SetRecordType(val string) {
	s.RecordType = val
}

// SetReview sets the value of Review.
func (s *ReviewedReference) SetReview(val ReviewedReferenceReview) {
	s.Review = val
}

type ReviewedReferenceReview struct {
	Kind string `json:"kind"`
}

// GetKind returns the value of Kind.
func (s *ReviewedReferenceReview) GetKind() string {
	return s.Kind
}

// SetKind sets the value of Kind.
func (s *ReviewedReferenceReview) SetKind(val string) {
	s.Kind = val
}
