// Code generated by ogen, DO NOT EDIT.

package unionapi

import (
	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/validate"
)

func (s *OrdinaryReference) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.RecordType.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "record_type",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s OrdinaryReferenceRecordType) Validate() error {
	switch s {
	case "draft":
		return nil
	case "template":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s Reference) Validate() error {
	switch s.Type {
	case OrdinaryReferenceReference:
		if err := s.OrdinaryReference.Validate(); err != nil {
			return err
		}
		return nil
	case ReviewedReferenceReference:
		return nil // no validation needed
	default:
		return errors.Errorf("invalid type %q", s.Type)
	}
}
