// Code generated by ogen, DO NOT EDIT.

package unionapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetReference implements getReference operation.
//
// GET /reference
func (UnimplementedHandler) GetReference(ctx context.Context) (r Reference, _ error) {
	return r, ht.ErrNotImplemented
}
