// Code generated by ogen, DO NOT EDIT.

package unionapi

import (
	"math/bits"
	"strconv"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/ogen-go/ogen/json"
	"github.com/ogen-go/ogen/validate"
)

// Encode encodes struct{} as json.
func (o OptNull) Encode(e *jx.Encoder) {
	if !o.Set {
		return
	}
	e.Null()
}

// Decode decodes struct{} from json.
func (o *OptNull) Decode(d *jx.Decoder) error {
	if o == nil {
		return errors.New("invalid: unable to decode OptNull to nil")
	}
	o.Set = true
	if err := d.Null(); err != nil {
		return err
	}
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OptNull) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OptNull) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *OrdinaryReference) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *OrdinaryReference) encodeFields(e *jx.Encoder) {
	{
		e.FieldStart("record_type")
		s.RecordType.Encode(e)
	}
	{
		if s.Review.Set {
			e.FieldStart("review")
			s.Review.Encode(e)
		}
	}
}

var jsonFieldsNameOfOrdinaryReference = [2]string{
	0: "record_type",
	1: "review",
}

// Decode decodes OrdinaryReference from json.
func (s *OrdinaryReference) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode OrdinaryReference to nil")
	}
	var requiredBitSet [1]uint8

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "record_type":
			requiredBitSet[0] |= 1 << 0
			if err := func() error {
				if err := s.RecordType.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"record_type\"")
			}
		case "review":
			if err := func() error {
				s.Review.Reset()
				if err := s.Review.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"review\"")
			}
		default:
			return errors.Errorf("unexpected field %q", k)
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode OrdinaryReference")
	}
	// Validate required fields.
	var failures []validate.FieldError
	for i, mask := range [1]uint8{
		0b00000001,
	} {
		if result := (requiredBitSet[i] & mask) ^ mask; result != 0 {
			// Mask only required fields and check equality to mask using XOR.
			//
			// If XOR result is not zero, result is not equal to expected, so some fields are missed.
			// Bits of fields which would be set are actually bits of missed fields.
			missed := bits.OnesCount8(result)
			for bitN := 0; bitN < missed; bitN++ {
				bitIdx := bits.TrailingZeros8(result)
				fieldIdx := i*8 + bitIdx
				var name string
				if fieldIdx < len(jsonFieldsNameOfOrdinaryReference) {
					name = jsonFieldsNameOfOrdinaryReference[fieldIdx]
				} else {
					name = strconv.Itoa(fieldIdx)
				}
				failures = append(failures, validate.FieldError{
					Name:  name,
					Error: validate.ErrFieldRequired,
				})
				// Reset bit.
				result &^= 1 << bitIdx
			}
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *OrdinaryReference) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OrdinaryReference) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes OrdinaryReferenceRecordType as json.
func (s OrdinaryReferenceRecordType) Encode(e *jx.Encoder) {
	e.Str(string(s))
}

// Decode decodes OrdinaryReferenceRecordType from json.
func (s *OrdinaryReferenceRecordType) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode OrdinaryReferenceRecordType to nil")
	}
	v, err := d.StrBytes()
	if err != nil {
		return err
	}
	// Try to use constant string.
	switch OrdinaryReferenceRecordType(v) {
	case OrdinaryReferenceRecordTypeDraft:
		*s = OrdinaryReferenceRecordTypeDraft
	case OrdinaryReferenceRecordTypeTemplate:
		*s = OrdinaryReferenceRecordTypeTemplate
	default:
		*s = OrdinaryReferenceRecordType(v)
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s OrdinaryReferenceRecordType) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *OrdinaryReferenceRecordType) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode encodes Reference as json.
func (s Reference) Encode(e *jx.Encoder) {
	switch s.Type {
	case OrdinaryReferenceReference:
		s.OrdinaryReference.Encode(e)
	case ReviewedReferenceReference:
		s.ReviewedReference.Encode(e)
	}
}

func (s Reference) encodeFields(e *jx.Encoder) {
	switch s.Type {
	case OrdinaryReferenceReference:
		s.OrdinaryReference.encodeFields(e)
	case ReviewedReferenceReference:
		s.ReviewedReference.encodeFields(e)
	}
}

// Decode decodes Reference from json.
func (s *Reference) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode Reference to nil")
	}
	// Sum type fields.
	if typ := d.Next(); typ != jx.Object {
		return errors.Errorf("unexpected json type %q", typ)
	}

	var found bool
	if err := d.Capture(func(d *jx.Decoder) error {
		return d.ObjBytes(func(d *jx.Decoder, key []byte) error {
			switch string(key) {
			case "review":
				// Multiple variants have this field - use type checking to discriminate
				typ := d.Next()
				switch typ {
				case jx.Null:
					match := OrdinaryReferenceReference
					if found && s.Type != match {
						s.Type = ""
						return errors.Errorf("multiple oneOf matches: (%v, %v)", s.Type, match)
					}
					found = true
					s.Type = match
				case jx.Object:
					match := ReviewedReferenceReference
					if found && s.Type != match {
						s.Type = ""
						return errors.Errorf("multiple oneOf matches: (%v, %v)", s.Type, match)
					}
					found = true
					s.Type = match
				default:
					// Unknown type for this field
					return d.Skip()
				}
			}
			return d.Skip()
		})
	}); err != nil {
		return errors.Wrap(err, "capture")
	}
	if !found {
		s.Type = OrdinaryReferenceReference
	}
	switch s.Type {
	case OrdinaryReferenceReference:
		if err := s.OrdinaryReference.Decode(d); err != nil {
			return err
		}
	case ReviewedReferenceReference:
		if err := s.ReviewedReference.Decode(d); err != nil {
			return err
		}
	default:
		return errors.Errorf("inferred invalid type: %s", s.Type)
	}
	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s Reference) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *Reference) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *ReviewedReference) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *ReviewedReference) encodeFields(e *jx.Encoder) {
	{
		e.FieldStart("record_type")
		e.Str("draft")
	}
	{
		e.FieldStart("review")
		s.Review.Encode(e)
	}
}

var jsonFieldsNameOfReviewedReference = [2]string{
	0: "record_type",
	1: "review",
}

// Decode decodes ReviewedReference from json.
func (s *ReviewedReference) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode ReviewedReference to nil")
	}
	var requiredBitSet [1]uint8

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "record_type":
			requiredBitSet[0] |= 1 << 0
			if err := func() error {
				if err := d.Capture(func(d *jx.Decoder) error {
					value, err := d.Raw()
					if err != nil {
						return err
					}
					equal, err := json.Equal(value, []byte("\"draft\""))
					if err != nil {
						return err
					}
					if !equal {
						return errors.New("unexpected constant value")
					}
					return nil
				}); err != nil {
					return err
				}
				v, err := d.Str()
				s.RecordType = string(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"record_type\"")
			}
		case "review":
			requiredBitSet[0] |= 1 << 1
			if err := func() error {
				if err := s.Review.Decode(d); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"review\"")
			}
		default:
			return errors.Errorf("unexpected field %q", k)
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode ReviewedReference")
	}
	// Validate required fields.
	var failures []validate.FieldError
	for i, mask := range [1]uint8{
		0b00000011,
	} {
		if result := (requiredBitSet[i] & mask) ^ mask; result != 0 {
			// Mask only required fields and check equality to mask using XOR.
			//
			// If XOR result is not zero, result is not equal to expected, so some fields are missed.
			// Bits of fields which would be set are actually bits of missed fields.
			missed := bits.OnesCount8(result)
			for bitN := 0; bitN < missed; bitN++ {
				bitIdx := bits.TrailingZeros8(result)
				fieldIdx := i*8 + bitIdx
				var name string
				if fieldIdx < len(jsonFieldsNameOfReviewedReference) {
					name = jsonFieldsNameOfReviewedReference[fieldIdx]
				} else {
					name = strconv.Itoa(fieldIdx)
				}
				failures = append(failures, validate.FieldError{
					Name:  name,
					Error: validate.ErrFieldRequired,
				})
				// Reset bit.
				result &^= 1 << bitIdx
			}
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *ReviewedReference) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *ReviewedReference) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}

// Encode implements json.Marshaler.
func (s *ReviewedReferenceReview) Encode(e *jx.Encoder) {
	e.ObjStart()
	s.encodeFields(e)
	e.ObjEnd()
}

// encodeFields encodes fields.
func (s *ReviewedReferenceReview) encodeFields(e *jx.Encoder) {
	{
		e.FieldStart("kind")
		e.Str("review")
	}
}

var jsonFieldsNameOfReviewedReferenceReview = [1]string{
	0: "kind",
}

// Decode decodes ReviewedReferenceReview from json.
func (s *ReviewedReferenceReview) Decode(d *jx.Decoder) error {
	if s == nil {
		return errors.New("invalid: unable to decode ReviewedReferenceReview to nil")
	}
	var requiredBitSet [1]uint8

	if err := d.ObjBytes(func(d *jx.Decoder, k []byte) error {
		switch string(k) {
		case "kind":
			requiredBitSet[0] |= 1 << 0
			if err := func() error {
				if err := d.Capture(func(d *jx.Decoder) error {
					value, err := d.Raw()
					if err != nil {
						return err
					}
					equal, err := json.Equal(value, []byte("\"review\""))
					if err != nil {
						return err
					}
					if !equal {
						return errors.New("unexpected constant value")
					}
					return nil
				}); err != nil {
					return err
				}
				v, err := d.Str()
				s.Kind = string(v)
				if err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return errors.Wrap(err, "decode field \"kind\"")
			}
		default:
			return errors.Errorf("unexpected field %q", k)
		}
		return nil
	}); err != nil {
		return errors.Wrap(err, "decode ReviewedReferenceReview")
	}
	// Validate required fields.
	var failures []validate.FieldError
	for i, mask := range [1]uint8{
		0b00000001,
	} {
		if result := (requiredBitSet[i] & mask) ^ mask; result != 0 {
			// Mask only required fields and check equality to mask using XOR.
			//
			// If XOR result is not zero, result is not equal to expected, so some fields are missed.
			// Bits of fields which would be set are actually bits of missed fields.
			missed := bits.OnesCount8(result)
			for bitN := 0; bitN < missed; bitN++ {
				bitIdx := bits.TrailingZeros8(result)
				fieldIdx := i*8 + bitIdx
				var name string
				if fieldIdx < len(jsonFieldsNameOfReviewedReferenceReview) {
					name = jsonFieldsNameOfReviewedReferenceReview[fieldIdx]
				} else {
					name = strconv.Itoa(fieldIdx)
				}
				failures = append(failures, validate.FieldError{
					Name:  name,
					Error: validate.ErrFieldRequired,
				})
				// Reset bit.
				result &^= 1 << bitIdx
			}
		}
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}

	return nil
}

// MarshalJSON implements stdjson.Marshaler.
func (s *ReviewedReferenceReview) MarshalJSON() ([]byte, error) {
	e := jx.Encoder{}
	s.Encode(&e)
	return e.Bytes(), nil
}

// UnmarshalJSON implements stdjson.Unmarshaler.
func (s *ReviewedReferenceReview) UnmarshalJSON(data []byte) error {
	d := jx.DecodeBytes(data)
	return s.Decode(d)
}
